# Generated by Django 2.2.12 on 2022-03-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=200)),
                ('HostIp', models.CharField(max_length=15)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArgumentText', models.CharField(max_length=100)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Module')),
            ],
        ),
    ]
